# Timeout in seconds that Limine will use before automatically booting.
timeout: 3
# randomise_memory: yes # Enable memory randomization for security and stability.

# The entry name that will be displayed in the boot menu.
/My Kernel
    # We use the Limine boot protocol.
    protocol: limine

    # Path to the kernel to boot. boot():/ represents the partition on which limine.conf is located.
    path: boot():/boot/kernel

    # To register a module, uncomment the following line and specify the module path.
    module_path: boot():/boot/Mik_8x16.psf
    module_string: kernel-font.psf

    module_path: boot():/boot/init
    module_string: init.elf

    module_path: boot():/boot/initrd.txt
    module_string: initrd
