# Timeout in seconds that Limine will use before automatically booting.
timeout: 0
randomise_memory: yes # Enable memory randomization for security and stability.

# The entry name that will be displayed in the boot menu.
/My Kernel
    # We use the Limine boot protocol.
    protocol: limine

    # Path to the kernel to boot. boot():/ represents the partition on which limine.conf is located.
    path: boot():/boot/kernel.elf

    # To register a module, uncomment the following line and specify the module path.
    # module_path: boot():/boot/kernel.elf
