#pragma once

#include "boot.h"
#include "early_console.h"
#include "emergency_console.h"
#include "interrupts.h"
#include "modules.h"
#include "physical_memory_manager.h"
#include "platform.h"
#include "string.h"
#include "syscalls.h"
#include "tasks.h"
#include "timer.h"
#include "virtual_address_allocator.h"
#include "virtual_memory_manager.h"
